spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.93:8848

server:
  port: 8081
test:
  config: 原始天尊
management:
  endpoints:
    web:
      exposure:
        include: "*"